## Assignment

### Part I

#### Clean your data

+ Read in temp_data.txt
    + It won't be easy! You'll need to find a way to clean the data
    + Try opening the file in a text editor first
+ Read in temp_X.csv
+ Merge the X variable from temp_X with the data from temp_data
+ Note that we discussed this in class, but it's something you'll just need to practice on your own. 
+ You will struggle with this and it's ok
+ Check out the documentation for read_csv() in the pandas package


### Part II

#### Run a linear regression
+ Using X to predict temperature 
+ Interpret your coefficients!
+ What is one potential use for this linear regression equation? 
+ What does this linear regression mean? 
+ Is this a good model? Why or why not?

In [1]:
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
%matplotlib inline

In [36]:
datatxt=pd.read_csv("C:/Users/irist_000/GA Data Science/DS-SF-32/lessons/lesson-5/temp_data.txt", delimiter='\t', names=('Station ID', 'Series Number', 'Date', 'Temperature (C)', 'Uncertainty (C)', 'Observations', 'Time of Observation'))

In [62]:
datacsv=pd.read_csv("C:/Users/irist_000/GA Data Science/DS-SF-32/lessons/lesson-5/temp_X.csv")
datacsv=datacsv.rename(columns = {'Station_ID':'Station ID', 'Series_Number':'Series Number'}) 
print datacsv

        Unnamed: 0  Station ID  Series Number      Date        X
0                0       25398              1  1986.708  79.8998
1                1       25398              1  1986.875  81.6674
2                2       25398              1  1986.958  82.8068
3                3       25398              1  1987.042  81.6458
4                4       25398              1  1987.125  82.3928
5                5       25398              1  1987.208  82.9040
6                6       25398              1  1987.292  83.4800
7                7       25398              1  1987.375  83.4818
8                8       25398              1  1987.542  81.1292
9                9       25398              1  1987.625  81.1292
10              10       25398              1  1987.708  81.3326
11              11       25398              1  1987.792  81.6134
12              12       25398              1  1987.875  82.6664
13              13       25398              1  1987.958  82.4198
14              14       25398              1  1988.042  82.1930
15              15       25398              1  1988.125  83.8274
16              16       25398              1  1988.208  83.7104
17              17       25398              1  1988.292  85.2332
18              18       25398              1  1988.458  81.0338
19              19       25398              1  1988.542  80.1932
20              20       25398              1  1988.625  80.7422
21              21       25398              1  1988.708  80.1662
22              22       25398              1  1988.792  80.3552
23              23       25398              1  1988.875  81.1328
24              24       25398              1  1989.042  80.2256
25              25       25398              1  1989.125  80.3930
26              26       25398              1  1989.208  82.6772
27              27       25398              1  1989.292  83.5664
28              28       25398              1  1989.375  82.1606
29              29       25398              1  1989.458  79.2338
...            ...         ...            ...       ...      ...
141607      141607      129867              1  2009.125  49.8920
141608      141608      129867              1  2009.208  54.3218
141609      141609      129867              1  2009.292  60.7334
141610      141610      129867              1  2009.375  69.3878
141611      141611      129867              1  2009.458  79.9340
141612      141612      129867              1  2009.542  80.7422
141613      141613      129867              1  2009.625  79.0970
141614      141614      129867              1  2009.708  73.3658
141615      141615      129867              1  2009.792  59.7416
141616      141616      129867              1  2009.875  55.7006
141617      141617      129867              1  2009.958  40.4132
141618      141618      129867              1  2010.042  40.2314
141619      141619      129867              1  2010.125  39.7508
141620      141620      129867              1  2010.208  50.8712
141621      141621      129867              1  2010.292  63.0338
141622      141622      129867              1  2010.375  72.5162
141623      141623      129867              1  2010.458  81.7664
141624      141624      129867              1  2010.542  82.6124
141625      141625      129867              1  2010.625  84.7742
141626      141626      129867              1  2010.708  75.4664
141627      141627      129867              1  2010.792  62.2256
141628      141628      129867              1  2010.875  51.9332
141629      141629      129867              1  2010.958  42.9026
141630      141630      129867              1  2011.042  39.0326
141631      141631      129867              1  2011.125  44.7134
141632      141632      129867              1  2011.208  55.1930
141633      141633      129867              1  2011.292  63.7340
141634      141634      129867              1  2011.375  68.6138
141635      141635      129867              1  2011.458  82.1336
141636      141636      129867              1  2011.542  87.0962

[141637 rows x 5 columns]

In [79]:
results = pd.merge(datatxt, datacsv, how= "inner", on= "Station ID")
print results
print results.columns

        Station ID Series Number_x    Date_x Temperature (C)  Uncertainty (C)  \
0           129822               1  2004.125           6.418           0.0516
1           129822               1  2004.125           6.418           0.0516
2           129822               1  2004.125           6.418           0.0516
3           129822               1  2004.125           6.418           0.0516
4           129822               1  2004.125           6.418           0.0516
5           129822               1  2004.125           6.418           0.0516
6           129822               1  2004.125           6.418           0.0516
7           129822               1  2004.125           6.418           0.0516
8           129822               1  2004.125           6.418           0.0516
9           129822               1  2004.125           6.418           0.0516
10          129822               1  2004.125           6.418           0.0516
11          129822               1  2004.125           6.418           0.0516
12          129822               1  2004.125           6.418           0.0516
13          129822               1  2004.125           6.418           0.0516
14          129822               1  2004.125           6.418           0.0516
15          129822               1  2004.125           6.418           0.0516
16          129822               1  2004.125           6.418           0.0516
17          129822               1  2004.125           6.418           0.0516
18          129822               1  2004.125           6.418           0.0516
19          129822               1  2004.125           6.418           0.0516
20          129822               1  2004.125           6.418           0.0516
21          129822               1  2004.125           6.418           0.0516
22          129822               1  2004.125           6.418           0.0516
23          129822               1  2004.125           6.418           0.0516
24          129822               1  2004.125           6.418           0.0516
25          129822               1  2004.125           6.418           0.0516
26          129822               1  2004.125           6.418           0.0516
27          129822               1  2004.125           6.418           0.0516
28          129822               1  2004.125           6.418           0.0516
29          129822               1  2004.125           6.418           0.0516
...            ...             ...       ...             ...              ...
2999170     129867               1  2011.542          30.609           0.0499
2999171     129867               1  2011.542          30.609           0.0499
2999172     129867               1  2011.542          30.609           0.0499
2999173     129867               1  2011.542          30.609           0.0499
2999174     129867               1  2011.542          30.609           0.0499
2999175     129867               1  2011.542          30.609           0.0499
2999176     129867               1  2011.542          30.609           0.0499
2999177     129867               1  2011.542          30.609           0.0499
2999178     129867               1  2011.542          30.609           0.0499
2999179     129867               1  2011.542          30.609           0.0499
2999180     129867               1  2011.542          30.609           0.0499
2999181     129867               1  2011.542          30.609           0.0499
2999182     129867               1  2011.542          30.609           0.0499
2999183     129867               1  2011.542          30.609           0.0499
2999184     129867               1  2011.542          30.609           0.0499
2999185     129867               1  2011.542          30.609           0.0499
2999186     129867               1  2011.542          30.609           0.0499
2999187     129867               1  2011.542          30.609           0.0499
2999188     129867               1  2011.542          30.609           0.0499
2999189     129867               1  2011.542          30.609           0.0499
2999190     129867               1  2011.542          30.609           0.0499
2999191     129867               1  2011.542          30.609           0.0499
2999192     129867               1  2011.542          30.609           0.0499
2999193     129867               1  2011.542          30.609           0.0499
2999194     129867               1  2011.542          30.609           0.0499
2999195     129867               1  2011.542          30.609           0.0499
2999196     129867               1  2011.542          30.609           0.0499
2999197     129867               1  2011.542          30.609           0.0499
2999198     129867               1  2011.542          30.609           0.0499
2999199     129867               1  2011.542          30.609           0.0499

         Observations  Time of Observation  Unnamed: 0  Series Number_y  \
0                29.0                 24.0      130777                1
1                29.0                 24.0      130778                1
2                29.0                 24.0      130779                1
3                29.0                 24.0      130780                1
4                29.0                 24.0      130781                1
5                29.0                 24.0      130782                1
6                29.0                 24.0      130783                1
7                29.0                 24.0      130784                1
8                29.0                 24.0      130785                1
9                29.0                 24.0      130786                1
10               29.0                 24.0      130787                1
11               29.0                 24.0      130788                1
12               29.0                 24.0      130789                1
13               29.0                 24.0      130790                1
14               29.0                 24.0      130791                1
15               29.0                 24.0      130792                1
16               29.0                 24.0      130793                1
17               29.0                 24.0      130794                1
18               29.0                 24.0      130795                1
19               29.0                 24.0      130796                1
20               29.0                 24.0      130797                1
21               29.0                 24.0      130798                1
22               29.0                 24.0      130799                1
23               29.0                 24.0      130800                1
24               29.0                 24.0      130801                1
25               29.0                 24.0      130802                1
26               29.0                 24.0      130803                1
27               29.0                 24.0      130804                1
28               29.0                 24.0      130805                1
29               29.0                 24.0      130806                1
...               ...                  ...         ...              ...
2999170          31.0                 24.0      141607                1
2999171          31.0                 24.0      141608                1
2999172          31.0                 24.0      141609                1
2999173          31.0                 24.0      141610                1
2999174          31.0                 24.0      141611                1
2999175          31.0                 24.0      141612                1
2999176          31.0                 24.0      141613                1
2999177          31.0                 24.0      141614                1
2999178          31.0                 24.0      141615                1
2999179          31.0                 24.0      141616                1
2999180          31.0                 24.0      141617                1
2999181          31.0                 24.0      141618                1
2999182          31.0                 24.0      141619                1
2999183          31.0                 24.0      141620                1
2999184          31.0                 24.0      141621                1
2999185          31.0                 24.0      141622                1
2999186          31.0                 24.0      141623                1
2999187          31.0                 24.0      141624                1
2999188          31.0                 24.0      141625                1
2999189          31.0                 24.0      141626                1
2999190          31.0                 24.0      141627                1
2999191          31.0                 24.0      141628                1
2999192          31.0                 24.0      141629                1
2999193          31.0                 24.0      141630                1
2999194          31.0                 24.0      141631                1
2999195          31.0                 24.0      141632                1
2999196          31.0                 24.0      141633                1
2999197          31.0                 24.0      141634                1
2999198          31.0                 24.0      141635                1
2999199          31.0                 24.0      141636                1

           Date_y        X
0        1986.708  57.0668
1        1986.875  45.3002
2        1986.958  42.5804
3        1987.042  41.6768
4        1987.125  45.8222
5        1987.208  48.2576
6        1987.292  51.2006
7        1987.375  55.0004
8        1987.458  57.8336
9        1987.542  59.7740
10       1987.625  59.7416
11       1987.708  57.3332
12       1987.792  51.5804
13       1987.875  48.7004
14       1987.958  40.9028
15       1988.042  40.9352
16       1988.125  43.9304
17       1988.208  45.3866
18       1988.292  49.6004
19       1988.375  54.2912
20       1988.458  57.2000
21       1988.542  59.4518
22       1988.625  60.0314
23       1988.708  56.4008
24       1988.792  52.8062
25       1988.875  46.6664
26       1988.958  43.0970
27       1989.042  41.0000
28       1989.125  35.0366
29       1989.208  44.1338
...           ...      ...
2999170  2009.125  49.8920
2999171  2009.208  54.3218
2999172  2009.292  60.7334
2999173  2009.375  69.3878
2999174  2009.458  79.9340
2999175  2009.542  80.7422
2999176  2009.625  79.0970
2999177  2009.708  73.3658
2999178  2009.792  59.7416
2999179  2009.875  55.7006
2999180  2009.958  40.4132
2999181  2010.042  40.2314
2999182  2010.125  39.7508
2999183  2010.208  50.8712
2999184  2010.292  63.0338
2999185  2010.375  72.5162
2999186  2010.458  81.7664
2999187  2010.542  82.6124
2999188  2010.625  84.7742
2999189  2010.708  75.4664
2999190  2010.792  62.2256
2999191  2010.875  51.9332
2999192  2010.958  42.9026
2999193  2011.042  39.0326
2999194  2011.125  44.7134
2999195  2011.208  55.1930
2999196  2011.292  63.7340
2999197  2011.375  68.6138
2999198  2011.458  82.1336
2999199  2011.542  87.0962

[2999200 rows x 11 columns]
Index([u'Station ID', u'Series Number_x', u'Date_x', u'Temperature (C)',
       u'Uncertainty (C)', u'Observations', u'Time of Observation',
       u'Unnamed: 0', u'Series Number_y', u'Date_y', u'X'],
      dtype='object')

In [90]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats
import seaborn as sns
import statsmodels.api as sm
from sklearn import linear_model

results[['X', 'Temperature (C)']].fillna(0.0, inplace=True)
X= results[["X"]]
Y= results[["Temperature (C)"]]

# model = sm.OLS(Y, X)
# results1 = model.fit()

model = linear_model.LinearRegression()
results1 = model.fit(X, Y)

# result = sm.ols(formula = "Y ~ X", data = results).fit()

# Print the coefficients
print model.intercept_, model.coef_

[-4.31909105] [[ 0.18097459]]

     X
X  1.0